const $ = (s) => document.querySelector(s);
const $$ = (s) => [...document.querySelectorAll(s)];
const STORAGE = {extra:'shiftAppExtraIncomes', custom:'shiftAppCustomPatterns', pattern:'shiftAppPattern', base:'shiftAppBaseSalary', sat:'shiftAppSaturdaySalary'};
const DEFAULT_BASE = 8300, DEFAULT_SAT = 5500;
let extraIncomes = readJSON(STORAGE.extra, {});
let customPatterns = readJSON(STORAGE.custom, []);
let savedPattern = readJSON(STORAGE.pattern, {work:2,off:2});
let workDaysPattern = Number(savedPattern.work)||2, offDaysPattern = Number(savedPattern.off)||2;
let baseSalary = Number(localStorage.getItem(STORAGE.base)) || DEFAULT_BASE;
let saturdaySalary = Number(localStorage.getItem(STORAGE.sat)) || DEFAULT_SAT;
const baseShiftDate = new Date(Date.UTC(2026,8,2));
const today = new Date();
const currentYear = today.getFullYear(), currentMonth = today.getMonth();
const monthNames=['Январь','Февраль','Март','Апрель','Май','Июнь','Июль','Август','Сентябрь','Октябрь','Ноябрь','Декабрь'];
const shortMonths=['янв.','февр.','мар.','апр.','мая','июн.','июл.','авг.','сент.','окт.','нояб.','дек.'];
let activeView='calendar', selectedDate=null;

function readJSON(key,fallback){try{return JSON.parse(localStorage.getItem(key)||JSON.stringify(fallback))}catch{return fallback}}
function savePattern(){localStorage.setItem(STORAGE.pattern,JSON.stringify({work:workDaysPattern,off:offDaysPattern}))}
function fmt(n){return Math.round(n).toLocaleString('ru-RU')+' ₽'}
function dateKey(d){return `${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-${String(d.getDate()).padStart(2,'0')}`}
function isWorkDay(date){const d=Date.UTC(date.getFullYear(),date.getMonth(),date.getDate());const diff=Math.floor((d-baseShiftDate.getTime())/86400000);const len=workDaysPattern+offDaysPattern;const pos=((diff%len)+len)%len;return pos<workDaysPattern}
function rate(date){return date.getDay()===6?saturdaySalary:baseSalary}
function calculateSalary(start,end){let salary=0,workDays=0,extra=0;for(let d=new Date(start);d<=end;d.setDate(d.getDate()+1)){const k=dateKey(d);if(isWorkDay(d)){salary+=rate(d);workDays++}if(extraIncomes[k]?.amount){const x=Number(extraIncomes[k].amount)||0;salary+=x;extra+=x}}return{salary,workDays,extra}}
function monthRange(y,m){return [new Date(y,m,1),new Date(y,m+1,0)]}
function currentMonthCalc(){return calculateSalary(...monthRange(currentYear,currentMonth))}
function nextPayLabel(){const day=today.getDate();return day<10?'10-го числа':day<25?'25-го числа':'10-го числа'}
function cyclePosition(date){const d=Date.UTC(date.getFullYear(),date.getMonth(),date.getDate());const diff=Math.floor((d-baseShiftDate.getTime())/86400000);const len=workDaysPattern+offDaysPattern;return ((diff%len)+len)%len}

function generateMonth(y,m){const month=document.createElement('div');month.className='month-block';const title=document.createElement('div');title.className='month-title';title.textContent=monthNames[m]+(y!==currentYear?' '+y:'');month.append(title);const grid=document.createElement('div');grid.className='days-grid';const first=new Date(y,m,1).getDay();const start=first===0?6:first-1;for(let i=0;i<start;i++){const e=document.createElement('div');e.className='day empty';grid.append(e)}const days=new Date(y,m+1,0).getDate();for(let day=1;day<=days;day++){const d=new Date(y,m,day),key=dateKey(d),el=document.createElement('button');el.type='button';el.className='day';el.textContent=day;el.setAttribute('aria-label',d.toLocaleDateString('ru-RU',{day:'numeric',month:'long',year:'numeric'}));if(d.toDateString()===today.toDateString())el.classList.add('today');if(isWorkDay(d))el.classList.add('work');if(extraIncomes[key])el.classList.add('has-extra');el.addEventListener('click',()=>openDayModal(d,key));grid.append(el)}month.append(grid);return month}
function renderCalendar(){const c=$('#calendar-container');c.innerHTML='';for(let m=0;m<12;m++)c.append(generateMonth(currentYear,m));$('#calendar-period-label').textContent=currentYear+' год';requestAnimationFrame(()=>{const target=c.querySelector('.month-block:nth-child('+(currentMonth+1)+')');target?.scrollIntoView({block:'start'})});updateHero()}
function updateHero(){const calc=currentMonthCalc(), working=isWorkDay(today), pos=cyclePosition(today);$('#today-status').textContent=working?'Рабочая смена':'Выходной день';$('#today-status').className='hero-status '+(working?'work':'off');$('#today-date').textContent=today.toLocaleDateString('ru-RU',{weekday:'long',day:'numeric',month:'long'});$('#hero-cycle').textContent=`${workDaysPattern} / ${offDaysPattern}`;$('#hero-next-pay').textContent=nextPayLabel();$('#hero-work-count').textContent=calc.workDays+' смен';$('#cycle-progress').style.width=((pos+1)/(workDaysPattern+offDaysPattern)*100)+'%';$('#hero-card').style.background=working?'linear-gradient(135deg,#10253b,#155b58 58%,#10a18e)':'linear-gradient(135deg,#182238,#39445b 60%,#657187)'}
function updatePayouts(){const [start,end]=monthRange(currentYear,currentMonth),calc=calculateSalary(start,end);const prevEnd=new Date(currentYear,currentMonth,0),pay10=calculateSalary(new Date(prevEnd.getFullYear(),prevEnd.getMonth(),15),prevEnd),pay25=calculateSalary(start,new Date(currentYear,currentMonth,15));const off=end.getDate()-calc.workDays;$('#payout-total').textContent=fmt(calc.salary);$('#payout-work-days').textContent=calc.workDays+' смен';$('#payout-period').textContent=monthNames[currentMonth].toLowerCase();$('#payout-10').textContent=fmt(pay10.salary);$('#payout-25').textContent=fmt(pay25.salary);$('#pay-work').textContent=calc.workDays;$('#pay-off').textContent=off;$('#pay-extra').textContent=fmt(calc.extra);$('#pay-average').textContent=calc.workDays?fmt(calc.salary/calc.workDays):'0 ₽';$('#payout-cycle').textContent=`${workDaysPattern} / ${offDaysPattern}`;const pct=calc.salary?Math.round(calc.extra/calc.salary*100):0;$('#payout-insight-title').textContent=calc.extra?`Доплаты составляют ${pct}% дохода`:'Расчёт готов';$('#payout-insight').textContent=calc.extra?'Учли все дополнительные выплаты, сохранённые в календаре.':'Смены и тарифы автоматически учитываются в расчёте.'}
function patterns(){return [{work:1,off:3},{work:2,off:2},{work:3,off:3},...customPatterns].filter((p,i,a)=>a.findIndex(x=>x.work===p.work&&x.off===p.off)===i)}
function renderSchedule(){const list=$('#schedule-list');list.innerHTML='';patterns().forEach(p=>{const active=p.work===workDaysPattern&&p.off===offDaysPattern;const b=document.createElement('button');b.className='schedule-option'+(active?' active':'');b.type='button';b.innerHTML=`<span class="schedule-option-main"><span class="schedule-option-icon">${p.work}/${p.off}</span><span><b>${p.work} / ${p.off}</b><small>${p.work} рабочих · ${p.off} выходных</small></span></span><span class="check">✓</span>`;b.addEventListener('click',()=>{workDaysPattern=p.work;offDaysPattern=p.off;savePattern();renderAll();showToast(`График ${p.work} / ${p.off} выбран`);});list.append(b)});$('#schedule-current').textContent=`${workDaysPattern} / ${offDaysPattern}`;$('#schedule-description').textContent=`${workDaysPattern} рабочих дня · ${offDaysPattern} выходных`;$('#schedule-wheel-work').textContent=workDaysPattern;$('#schedule-wheel-off').textContent=offDaysPattern}
function updateSettings(){ $('#base-salary-input').value=baseSalary;$('#saturday-salary-input').value=saturdaySalary }
function renderAll(){renderCalendar();updatePayouts();renderSchedule();updateSettings()}
function showToast(msg){const t=$('#toast');t.textContent=msg;t.classList.add('show');clearTimeout(showToast.timer);showToast.timer=setTimeout(()=>t.classList.remove('show'),2200)}
function openModal(id){$('#'+id).classList.remove('hidden');document.body.classList.add('modal-open')}
function closeModal(id){$('#'+id).classList.add('hidden');if(!$$('.modal:not(.hidden)').length)document.body.classList.remove('modal-open')}
function openDayModal(d,key){selectedDate=key;$('#modal-date-title').textContent=d.toLocaleDateString('ru-RU',{day:'numeric',month:'long',year:'numeric'});$('#extra-amount').value=extraIncomes[key]?.amount||'';$('#extra-note').value=extraIncomes[key]?.note||'';openModal('day-modal')}
function navigate(view){if(activeView===view)return;activeView=view;$$('.view').forEach(v=>v.classList.toggle('active',v.dataset.view===view));$$('.nav-item').forEach(n=>n.classList.toggle('active',n.dataset.target===view));const meta={calendar:['МОЙ ГРАФИК','Сегодня'],payouts:['ФИНАНСЫ','Выплаты'],schedule:['РЕЖИМ РАБОТЫ','График'],settings:['ПРИЛОЖЕНИЕ','Настройки']}[view];$('#screen-eyebrow').textContent=meta[0];$('#screen-title').textContent=meta[1];$('#header-action').style.visibility=view==='settings'?'hidden':'visible';if(view==='calendar')renderCalendar();if(view==='payouts')updatePayouts();if(view==='schedule')renderSchedule()}

$$('.nav-item').forEach(btn=>btn.addEventListener('click',()=>navigate(btn.dataset.target)));
$('#header-action').addEventListener('click',()=>{navigate('calendar');setTimeout(()=>$('#calendar-container .month-block:nth-child('+(currentMonth+1)+')')?.scrollIntoView({behavior:'smooth',block:'start'}),40)});
$('#jump-today-btn').addEventListener('click',()=>{$('#calendar-container .month-block:nth-child('+(currentMonth+1)+')')?.scrollIntoView({behavior:'smooth',block:'start'});showToast('Сегодняшний месяц открыт')});
$('#hero-cycle').addEventListener('click',()=>navigate('schedule'));
$('#open-shift-modal').addEventListener('click',()=>openModal('shift-modal'));
$('#close-shift-btn').addEventListener('click',()=>closeModal('shift-modal'));$('#close-day-btn').addEventListener('click',()=>closeModal('day-modal'));
$$('[data-close-modal]').forEach(x=>x.addEventListener('click',()=>closeModal(x.dataset.closeModal)));
$('#save-day-btn').addEventListener('click',()=>{if(!selectedDate)return;const amount=Number($('#extra-amount').value)||0,note=$('#extra-note').value.trim();if(amount||note)extraIncomes[selectedDate]={amount,note};else delete extraIncomes[selectedDate];localStorage.setItem(STORAGE.extra,JSON.stringify(extraIncomes));closeModal('day-modal');renderAll();showToast(amount?'Доплата сохранена':'Данные дня обновлены')});
$('#save-shift-btn').addEventListener('click',()=>{const w=parseInt($('#new-work-days').value,10),o=parseInt($('#new-off-days').value,10);if(!Number.isInteger(w)||!Number.isInteger(o)||w<1||o<1||w>31||o>31){showToast('Введите значения от 1 до 31');return}if(!customPatterns.some(p=>p.work===w&&p.off===o))customPatterns.push({work:w,off:o});localStorage.setItem(STORAGE.custom,JSON.stringify(customPatterns));workDaysPattern=w;offDaysPattern=o;savePattern();$('#new-work-days').value='';$('#new-off-days').value='';closeModal('shift-modal');renderAll();navigate('schedule');showToast(`График ${w} / ${o} добавлен`)});
$('#base-salary-input').addEventListener('change',e=>{baseSalary=Math.max(0,Number(e.target.value)||0);localStorage.setItem(STORAGE.base,baseSalary);renderAll();showToast('Обычный тариф сохранён')});
$('#saturday-salary-input').addEventListener('change',e=>{saturdaySalary=Math.max(0,Number(e.target.value)||0);localStorage.setItem(STORAGE.sat,saturdaySalary);renderAll();showToast('Субботний тариф сохранён')});
$('#settings-today').addEventListener('click',()=>navigate('calendar'));
$('#settings-reset').addEventListener('click',()=>{if(!confirm('Сбросить свои графики и дополнительные выплаты?'))return;extraIncomes={};customPatterns=[];localStorage.removeItem(STORAGE.extra);localStorage.removeItem(STORAGE.custom);workDaysPattern=2;offDaysPattern=2;savePattern();renderAll();showToast('Данные сброшены')});
document.addEventListener('keydown',e=>{if(e.key==='Escape')$$('.modal:not(.hidden)').forEach(m=>closeModal(m.id))});

window.addEventListener('load',()=>{renderAll();const loader=$('#loader-text');setTimeout(()=>loader.textContent='Готовим ваш график…',450);setTimeout(()=>{loader.textContent='Готово';$('#splash-screen').classList.add('is-hidden');$('#app-shell').classList.add('ready');$('#app-shell').setAttribute('aria-hidden','false')},850)});
