const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
const STORAGE={extra:'shiftAppExtraIncomes',custom:'shiftAppCustomPatterns',pattern:'shiftAppPattern',base:'shiftAppBaseSalary',sat:'shiftAppSaturdaySalary'};
const DEFAULT_BASE=8300,DEFAULT_SAT=5500;
const monthNames=['Январь','Февраль','Март','Апрель','Май','Июнь','Июль','Август','Сентябрь','Октябрь','Ноябрь','Декабрь'];
const today=new Date(), currentYear=today.getFullYear(), currentMonth=today.getMonth(), baseShiftDate=new Date(Date.UTC(2026,8,2));
let extraIncomes=readJSON(STORAGE.extra,{}), customPatterns=readJSON(STORAGE.custom,[]), savedPattern=readJSON(STORAGE.pattern,{work:2,off:2});
let workDaysPattern=Number(savedPattern.work)||2, offDaysPattern=Number(savedPattern.off)||2;
let baseSalary=Number(localStorage.getItem(STORAGE.base)); if(!Number.isFinite(baseSalary)||baseSalary<0)baseSalary=DEFAULT_BASE;
let saturdaySalary=Number(localStorage.getItem(STORAGE.sat)); if(!Number.isFinite(saturdaySalary)||saturdaySalary<0)saturdaySalary=DEFAULT_SAT;
let activeView='calendar', selectedDate=null;
function readJSON(k,f){try{const v=JSON.parse(localStorage.getItem(k));return v??f}catch{return f}}
function persist(k,v){localStorage.setItem(k,typeof v==='string'?v:JSON.stringify(v))}
function fmt(n){return Math.round(Number(n)||0).toLocaleString('ru-RU')+' ₽'}
function dateKey(d){return `${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-${String(d.getDate()).padStart(2,'0')}`}
function isWorkDay(date){const d=Date.UTC(date.getFullYear(),date.getMonth(),date.getDate()),diff=Math.floor((d-baseShiftDate.getTime())/86400000),len=workDaysPattern+offDaysPattern,pos=((diff%len)+len)%len;return pos<workDaysPattern}
function rate(d){return d.getDay()===6?saturdaySalary:baseSalary}
function calculateSalary(start,end){let salary=0,workDays=0,extra=0;for(let d=new Date(start);d<=end;d.setDate(d.getDate()+1)){const k=dateKey(d);if(isWorkDay(d)){salary+=rate(d);workDays++}const x=Number(extraIncomes[k]?.amount)||0;if(x){salary+=x;extra+=x}}return{salary,workDays,extra}}
function monthRange(y,m){return[new Date(y,m,1),new Date(y,m+1,0)]}
function cyclePosition(d){const x=Date.UTC(d.getFullYear(),d.getMonth(),d.getDate()),diff=Math.floor((x-baseShiftDate.getTime())/86400000),len=workDaysPattern+offDaysPattern;return((diff%len)+len)%len}
function nextPay(){const day=today.getDate();return day<10?'10-го числа':day<25?'25-го числа':'10-го числа'}
function formatDayShort(d){return ['ПН','ВТ','СР','ЧТ','ПТ','СБ','ВС'][((d.getDay()+6)%7)]}
function formatShiftDate(d){return d.toLocaleDateString('ru-RU',{day:'numeric',month:'short'}).replace('.','')}
function getWeekStart(d){const x=new Date(d);const day=x.getDay()||7;x.setDate(x.getDate()-day+1);x.setHours(12,0,0,0);return x}
function nextWorkDate(from){const d=new Date(from);d.setHours(12,0,0,0);for(let i=1;i<=workDaysPattern+offDaysPattern+2;i++){d.setDate(d.getDate()+1);if(isWorkDay(d))return d}return d}
function renderWeekStrip(){const root=$('#week-strip');if(!root)return;root.innerHTML='';const start=getWeekStart(today);for(let i=0;i<7;i++){const d=new Date(start);d.setDate(start.getDate()+i);const b=document.createElement('button');b.type='button';b.className='week-day'+(d.toDateString()===today.toDateString()?' active':'')+(isWorkDay(d)?' is-work':'');b.innerHTML=`<span>${formatDayShort(d)}</span><b>${d.getDate()}</b>`;b.addEventListener('click',()=>{if(d.getMonth()!==currentMonth){$('#month-'+d.getMonth())?.scrollIntoView({behavior:'smooth',block:'start'})}else{$('#month-'+d.getMonth())?.scrollIntoView({behavior:'smooth',block:'start'})}toast(`${d.toLocaleDateString('ru-RU',{weekday:'long',day:'numeric',month:'long'})}: ${isWorkDay(d)?'рабочий день':'выходной'}`)});root.append(b)}}
function updateTodayInsight(){const working=isWorkDay(today);const start=new Date(currentYear,currentMonth,1);const endOfToday=new Date(today);endOfToday.setHours(23,59,59,999);const monthEnd=new Date(currentYear,currentMonth+1,0);let worked=0,remaining=0;for(let d=new Date(start);d<=monthEnd;d.setDate(d.getDate()+1)){if(isWorkDay(d)){if(d<=today)worked++;else remaining++}}const next=nextWorkDate(today);$('#insight-title').textContent=working?'Рабочая смена':'Выходной';$('#insight-subtitle').textContent=working?`Сегодня рабочий день по графику ${workDaysPattern} / ${offDaysPattern}.`:`Сегодня можно выдохнуть — следующая смена ${formatShiftDate(next)}.`;$('#insight-badge-text').textContent=working?'В РАБОТЕ':'ОТДЫХ';$('#today-insight').classList.toggle('working',working);$('#worked-so-far').textContent=`${worked} ${plural(worked,'смена','смены','смен')}`;$('#work-left').textContent=`${remaining} ${plural(remaining,'смена','смены','смен')}`;$('#next-shift').textContent=formatShiftDate(next)}
function renderCalendar(){const c=$('#calendar');c.innerHTML='';for(let m=0;m<12;m++){const box=document.createElement('section');box.className='month';box.id=`month-${m}`;box.innerHTML=`<div class="month-title"><span>${monthNames[m]}</span><small>${currentYear}</small></div><div class="month-weekdays"><span>ПН</span><span>ВТ</span><span>СР</span><span>ЧТ</span><span>ПТ</span><span>СБ</span><span>ВС</span></div><div class="days"></div>`;const grid=box.querySelector('.days'),first=new Date(currentYear,m,1).getDay(),offset=first===0?6:first-1;for(let i=0;i<offset;i++){const e=document.createElement('span');e.className='day empty';grid.append(e)}const count=new Date(currentYear,m+1,0).getDate();for(let n=1;n<=count;n++){const d=new Date(currentYear,m,n),key=dateKey(d),b=document.createElement('button');b.type='button';b.className='day';b.textContent=n;b.setAttribute('aria-label',d.toLocaleDateString('ru-RU',{day:'numeric',month:'long'}));if(d.toDateString()===today.toDateString())b.classList.add('today');if(isWorkDay(d))b.classList.add('work');if(extraIncomes[key])b.classList.add('has-extra');b.addEventListener('click',()=>openExtra(d));grid.append(b)}c.append(box)}$('#calendar-period').textContent=currentYear;renderWeekStrip();updateTodayInsight();requestAnimationFrame(()=>$('#month-'+currentMonth)?.scrollIntoView({block:'start'}));updateHero()}
function updateHero(){const calc=calculateSalary(...monthRange(currentYear,currentMonth)),working=isWorkDay(today),pos=cyclePosition(today);$('#today-status').textContent=working?'Сегодня работаю':'Сегодня выходной';$('#today-date').textContent=today.toLocaleDateString('ru-RU',{weekday:'long',day:'numeric',month:'long'});$('#hero-weekday').textContent=today.toLocaleDateString('ru-RU',{weekday:'long'}); $('#hero-cycle').textContent=`${workDaysPattern} / ${offDaysPattern}`;$('#hero-next-pay').textContent=nextPay();$('#hero-work-count').textContent=`${calc.workDays} смен`;$('#cycle-progress').style.width=`${((pos+1)/(workDaysPattern+offDaysPattern))*100}%`}
function updateFinance(){const [start,end]=monthRange(currentYear,currentMonth),calc=calculateSalary(start,end),prevEnd=new Date(currentYear,currentMonth,0),pay10=calculateSalary(new Date(prevEnd.getFullYear(),prevEnd.getMonth(),16),prevEnd),pay25=calculateSalary(start,new Date(currentYear,currentMonth,15));const off=end.getDate()-calc.workDays;$('#payout-total').textContent=fmt(calc.salary);$('#payout-work-days').textContent=`${calc.workDays} смен`;$('#payout-period').textContent=monthNames[currentMonth].toLowerCase();$('#payout-10').textContent=fmt(pay10.salary);$('#payout-25').textContent=fmt(pay25.salary);$('#pay-work').textContent=calc.workDays;$('#pay-off').textContent=off;$('#pay-extra').textContent=fmt(calc.extra);$('#pay-average').textContent=calc.workDays?fmt(calc.salary/calc.workDays):'0 ₽';const entries=monthExtras();$('#extra-title').textContent=entries.length?`${entries.length} ${plural(entries.length,'доплата','доплаты','доплат')}`:'Доплаты';$('#extra-summary').textContent=entries.length?`За месяц добавлено ${fmt(calc.extra)} дополнительных выплат.`:'Добавляйте премии и доплаты — они автоматически попадут в расчёт.'}
function monthExtras(){return Object.entries(extraIncomes).filter(([k,v])=>{const [y,m]=k.split('-').map(Number);return y===currentYear&&m-1===currentMonth&&Number(v?.amount)||v?.note}).sort(([a],[b])=>a.localeCompare(b))}
function plural(n,a,b,c){const x=n%100;return x>=11&&x<=14?c:n%10===1?a:n%10>=2&&n%10<=4?b:c}
function patterns(){return[{work:1,off:3},{work:2,off:2},{work:3,off:3},...customPatterns].filter((p,i,a)=>a.findIndex(x=>x.work===p.work&&x.off===p.off)===i)}
function renderSchedule(){const list=$('#schedule-list');list.innerHTML='';patterns().forEach(p=>{const b=document.createElement('button');b.type='button';b.className='schedule-option'+(p.work===workDaysPattern&&p.off===offDaysPattern?' active':'');b.innerHTML=`<span class="schedule-main"><span class="schedule-icon">${p.work}/${p.off}</span><span><b>${p.work} / ${p.off}</b><small>${p.work} рабочих · ${p.off} выходных</small></span></span><span class="check">✓</span>`;b.addEventListener('click',()=>{workDaysPattern=p.work;offDaysPattern=p.off;persist(STORAGE.pattern,{work:p.work,off:p.off});renderAll();toast(`График ${p.work} / ${p.off} выбран`)});list.append(b)});$('#schedule-current').textContent=`${workDaysPattern} / ${offDaysPattern}`;$('#schedule-description').textContent=`${workDaysPattern} рабочих дня · ${offDaysPattern} выходных`;$('#schedule-work').textContent=workDaysPattern;$('#schedule-off').textContent=offDaysPattern}
function updateSettings(){$('#base-input').value=baseSalary;$('#sat-input').value=saturdaySalary}
function renderAll(){renderCalendar();updateFinance();renderSchedule();updateSettings()}
function openSheet(id){$('#'+id).classList.remove('hidden');document.body.style.overflow='hidden'}
function closeSheet(id){$('#'+id).classList.add('hidden');if(!$$('.sheet:not(.hidden)').length)document.body.style.overflow=''}
function openExtra(d=new Date()){selectedDate=dateKey(d);$('#day-title').textContent='Доплата';$('#extra-amount').value=extraIncomes[selectedDate]?.amount??'';$('#extra-note').value=extraIncomes[selectedDate]?.note??'';openSheet('day-modal')}
function saveExtra(){const k=selectedDate;if(!k){toast('Сначала выберите день в календаре');return}const amount=Math.max(0,Number($('#extra-amount').value)||0),note=$('#extra-note').value.trim();if(amount===0&&!note){delete extraIncomes[k]}else{extraIncomes[k]={amount,note}}persist(STORAGE.extra,extraIncomes);closeSheet('day-modal');renderAll();toast(amount?`Доплата ${fmt(amount)} сохранена`:'Доплата удалена')}
function renderExtraList(){const list=$('#extra-list'),entries=monthExtras();list.innerHTML='';if(!entries.length){list.innerHTML='<div class="empty-extra">В этом месяце пока нет доплат.</div>';return}entries.forEach(([k,v])=>{const d=new Date(`${k}T12:00:00`),row=document.createElement('div');row.className='extra-row';row.innerHTML=`<div class="extra-date">${d.toLocaleDateString('ru-RU',{day:'2-digit',month:'short'}).replace('.','')}</div><main><b>${fmt(v.amount)}</b><span>${v.note||'Дополнительная выплата'}</span></main><button class="extra-delete" aria-label="Удалить">×</button>`;row.querySelector('.extra-delete').addEventListener('click',()=>{delete extraIncomes[k];persist(STORAGE.extra,extraIncomes);renderExtraList();renderAll();toast('Доплата удалена')});list.append(row)})}
function navigate(view){if(activeView===view)return;activeView=view;$$('.view').forEach(v=>v.classList.toggle('active',v.dataset.view===view));$$('.tab').forEach(t=>t.classList.toggle('active',t.dataset.target===view));const meta={calendar:['МОЙ ГРАФИК','Сегодня'],payouts:['ФИНАНСЫ','Выплаты'],schedule:['РЕЖИМ РАБОТЫ','График'],settings:['ПРИЛОЖЕНИЕ','Настройки']}[view];$('#eyebrow').textContent=meta[0];$('#title').textContent=meta[1];if(view==='calendar')renderCalendar();if(view==='payouts')updateFinance();if(view==='schedule')renderSchedule()}
function toast(msg){const t=$('#toast');t.textContent=msg;t.classList.add('show');clearTimeout(toast.timer);toast.timer=setTimeout(()=>t.classList.remove('show'),2300)}
$$('.tab').forEach(b=>b.addEventListener('click',()=>navigate(b.dataset.target)));
$('#jump-today').addEventListener('click',()=>$('#month-'+currentMonth)?.scrollIntoView({behavior:'smooth',block:'start'}));
$('#hero-cycle').addEventListener('click',()=>navigate('schedule'));
$('#add-extra-finance').addEventListener('click',()=>openExtra(new Date()));
$('#open-extra-list').addEventListener('click',()=>{renderExtraList();openSheet('extra-list-modal')});
$('#list-add-extra').addEventListener('click',()=>{closeSheet('extra-list-modal');openExtra()});
$('#save-extra').addEventListener('click',saveExtra);
$('#open-shift').addEventListener('click',()=>openSheet('shift-modal'));
$('#save-shift').addEventListener('click',()=>{const w=Number.parseInt($('#new-work').value,10),o=Number.parseInt($('#new-off').value,10);if(!Number.isInteger(w)||!Number.isInteger(o)||w<1||o<1||w>31||o>31){toast('Введите числа от 1 до 31');return}if(!customPatterns.some(p=>p.work===w&&p.off===o))customPatterns.push({work:w,off:o});persist(STORAGE.custom,customPatterns);workDaysPattern=w;offDaysPattern=o;persist(STORAGE.pattern,{work:w,off:o});$('#new-work').value='';$('#new-off').value='';closeSheet('shift-modal');renderAll();toast(`График ${w} / ${o} добавлен`)});
$$('[data-close]').forEach(b=>b.addEventListener('click',()=>closeSheet(b.dataset.close)));
$('#base-input').addEventListener('change',e=>{baseSalary=Math.max(0,Number(e.target.value)||0);persist(STORAGE.base,baseSalary);renderAll();toast('Тариф сохранён')});
$('#sat-input').addEventListener('change',e=>{saturdaySalary=Math.max(0,Number(e.target.value)||0);persist(STORAGE.sat,saturdaySalary);renderAll();toast('Субботний тариф сохранён')});
$('#settings-today').addEventListener('click',()=>navigate('calendar'));
$('#settings-reset').addEventListener('click',()=>{if(!confirm('Сбросить доплаты и созданные графики?'))return;extraIncomes={};customPatterns=[];localStorage.removeItem(STORAGE.extra);localStorage.removeItem(STORAGE.custom);workDaysPattern=2;offDaysPattern=2;persist(STORAGE.pattern,{work:2,off:2});renderAll();toast('Данные сброшены')});
document.addEventListener('keydown',e=>{if(e.key==='Escape')$$('.sheet:not(.hidden)').forEach(s=>closeSheet(s.id))});
window.addEventListener('load',()=>{renderAll();const status=$('#splash-status');setTimeout(()=>status.textContent='Синхронизируем ваш график',350);setTimeout(()=>status.textContent='Почти готово',700);setTimeout(()=>{$('#splash').classList.add('hide');$('#app').classList.add('ready');$('#app').setAttribute('aria-hidden','false')},1050)});
